# SPDX-FileCopyrightText: 2025 - 2026 hazzuk
#
# SPDX-License-Identifier: AGPL-3.0-only

---

karo_compose_justfile_stack: all

# docker will start stacks in this order
# docker will stop stacks in reverse order
karo_compose_stacks:
  core:
    - traefik
    - pocketid
  extra:
    - proxy
    - whoami
    - godns
    - gluetun
    - qbittorrent
    - prowlarr
    - radarr
    - sonarr
    - seerr
    - jellyfin
    - ntfy
    - glance

karo_compose_restart_policy: unless-stopped
karo_compose_timezone: "Europe/London"

karo_compose_root_domain: example.com

# oidc

karo_compose_oidc_subdomain: auth
karo_compose_oidc_domain: "{{ karo_compose_oidc_subdomain }}.{{ karo_compose_root_domain }}" # e.g. auth.example.com
karo_compose_oidc_url: "https://{{ karo_compose_oidc_domain }}" # e.g. https://auth.example.com

karo_compose_oidc_authorization_path: "/authorize"
karo_compose_oidc_authorization_url: "{{ karo_compose_oidc_url }}{{ karo_compose_oidc_authorization_path }}"

karo_compose_oidc_discovery_path: "/.well-known/openid-configuration"
karo_compose_oidc_discovery_url: "{{ karo_compose_oidc_url }}{{ karo_compose_oidc_discovery_path }}"

karo_compose_oidc_token_path: "/api/oidc/token"
karo_compose_oidc_token_url: "{{ karo_compose_oidc_url }}{{ karo_compose_oidc_token_path }}"

karo_compose_oidc_userinfo_path: "/api/oidc/userinfo"
karo_compose_oidc_userinfo_url: "{{ karo_compose_oidc_url }}{{ karo_compose_oidc_userinfo_path }}"

karo_compose_oidc_logout_path: "/api/oidc/end-session"
karo_compose_oidc_logout_url: "{{ karo_compose_oidc_url }}{{ karo_compose_oidc_logout_path }}"

karo_compose_oidc_certificate_path: "/.well-known/jwks.json"
karo_compose_oidc_certificate_url: "{{ karo_compose_oidc_url }}{{ karo_compose_oidc_certificate_path }}"

karo_compose_oidc_provider_name: "PocketID"

karo_compose_oidc_admin_group: "admin"

# core stacks
# ---

# pocketid

karo_compose_pocketid_enabled: true
karo_compose_pocketid_image: ghcr.io/pocket-id/pocket-id
karo_compose_pocketid_version: v2.6.2@sha256:1cc51e5b36fa7ec31368d3efb24ba362be6dce20f3cc0a2852843527bd5110f0
karo_compose_pocketid_log_level: info # debug, info, warn, error

karo_compose_pocketid_encryption_key: "" # secret (`openssl rand -base64 32`)
karo_compose_pocketid_maxmind_license_key: "" # secret

# traefik

karo_compose_traefik_enabled: true
karo_compose_traefik_image: docker.io/traefik
karo_compose_traefik_version: v3.6.15@sha256:8cb20d16e01a53d8d7f7696ac2f1af7d200d5c9984d226ce2299731d9eab6d6c
karo_compose_traefik_dashboard_domain: "traefik.{{ karo_compose_root_domain }}"
karo_compose_traefik_dashboard_forward_auth_enabled: true
karo_compose_traefik_log_level: debug # trace, debug, info, warn, error, fatal, panic

karo_compose_traefik_dashboard_enabled: true

karo_compose_traefik_custom_domains_raw: |
  # - main: "*.int.{{ karo_compose_root_domain }}"

karo_compose_traefik_acme_staging_enabled: true

karo_compose_traefik_acme_ca_server_url: "https://acme-v02.api.letsencrypt.org/directory" # "https://acme.zerossl.com/v2/DV90"
karo_compose_traefik_acme_staging_ca_server_url: "https://acme-staging-v02.api.letsencrypt.org/directory"

karo_compose_traefik_acme_email: cert@example.com
karo_compose_traefik_acme_zone_api_token: "" # secret
karo_compose_traefik_acme_dns_api_token: "" # secret

# traefik tinyauth

karo_compose_traefik_tinyauth_image: ghcr.io/steveiliop56/tinyauth
karo_compose_traefik_tinyauth_version: v5.0.7-distroless@sha256:e31ae2bac566cfe4687a8a54121a884ce25c4869995075f8e7e3d352bcd59241
karo_compose_traefik_tinyauth_domain: "tinyauth.{{ karo_compose_root_domain }}"
karo_compose_traefik_tinyauth_log_level: info # trace, debug, info, warn, error, fatal, panic

karo_compose_traefik_tinyauth_oidc_client_id: ""
karo_compose_traefik_tinyauth_oidc_client_secret: "" # secret

# traefik cetusguard

karo_compose_traefik_cetusguard_image: docker.io/hectorm/cetusguard
karo_compose_traefik_cetusguard_version: v1.1.3@sha256:b3dc5d2042869dd714c75985d94bb8c259df53b325ec6b1a2b57bcc3eac17689
karo_compose_traefik_cetusguard_log_level: 7 # 0-7 (min to max verbosity)

# extra stacks
# ---

# glance

karo_compose_glance_enabled: false
karo_compose_glance_image: docker.io/glanceapp/glance
karo_compose_glance_version: v0.8.4@sha256:6df86a7e8868d1eda21f35205134b1962c422957e42a0c44d4717c8e8f741b1a
karo_compose_glance_domain: "glance.{{ karo_compose_root_domain }}"
karo_compose_glance_forward_auth_enabled: true

karo_compose_glance_config_raw: |
  # glance config

# gluetun

karo_compose_gluetun_enabled: false
karo_compose_gluetun_image: docker.io/qmcgaw/gluetun
karo_compose_gluetun_version: v3.41.1@sha256:1a5bf4b4820a879cdf8d93d7ef0d2d963af56670c9ebff8981860b6804ebc8ab
karo_compose_gluetun_log_level: info # debug, info, warning, error

karo_compose_gluetun_firewall_vpn_input_ports: ""

karo_compose_gluetun_wireguard_config_raw: | # secret
  # wireguard config

# godns

karo_compose_godns_enabled: false
karo_compose_godns_image: docker.io/timothyye/godns
karo_compose_godns_version: v3.4.1@sha256:d9a043164b256ab9d7ab03a7619bfe2292a2ab2b6e5e3151e818edb63249b1de
karo_compose_godns_debug_info_enabled: false

karo_compose_godns_subdomain: home

karo_compose_godns_dns_api_token: "" # secret

# jellyfin

karo_compose_jellyfin_enabled: false
karo_compose_jellyfin_image: docker.io/jellyfin/jellyfin
karo_compose_jellyfin_version: 10.11.8@sha256:1694ff069f0c9dafb283c36765175606866769f5d72f2ed56b6a0f1be922fc37
karo_compose_jellyfin_domain: "jellyfin.{{ karo_compose_root_domain }}"

karo_compose_jellyfin_movies_media_path: "" # e.g. /media/drive1/data/media/movies
karo_compose_jellyfin_series_media_path: "" # e.g. /media/drive1/data/media/series

# ntfy

karo_compose_ntfy_enabled: false
karo_compose_ntfy_image: docker.io/binwiederhier/ntfy
karo_compose_ntfy_version: v2.22.0@sha256:d8b3408c75d5ae78e03339af6103e7e6195e56573eea6f1ad34bb4dc4f44f340
karo_compose_ntfy_domain: "ntfy.{{ karo_compose_root_domain }}"
karo_compose_ntfy_log_level: info # trace, debug, info, warn, error

karo_compose_ntfy_auth_users: "" # https://docs.ntfy.sh/config/#users-via-the-config
karo_compose_ntfy_auth_access: "" # https://docs.ntfy.sh/config/#acl-entries-via-the-config
karo_compose_ntfy_auth_tokens: "" # https://docs.ntfy.sh/config/#tokens-via-the-config

# prowlarr

karo_compose_prowlarr_enabled: false
karo_compose_prowlarr_image: docker.io/linuxserver/prowlarr
karo_compose_prowlarr_version: 2.3.5.5327-ls144@sha256:b4204e18666179472225935b443a99cf6c66dcb7bbc2d35034427a3851f13135
karo_compose_prowlarr_domain: "prowlarr.{{ karo_compose_root_domain }}"
karo_compose_prowlarr_forward_auth_enabled: true

# proxy

karo_compose_proxy_client_enabled: false
karo_compose_proxy_server_enabled: false

karo_compose_proxy_enabled: "{{ karo_compose_proxy_server_enabled }}"

karo_compose_proxy_client_wireguard_ipv4: 10.25.0.2
karo_compose_proxy_server_wireguard_ipv4: 10.25.0.1

karo_compose_proxy_server_wireguard_port: 52525

# proxy haproxy

karo_compose_proxy_haproxy_image: docker.io/haproxy
karo_compose_proxy_haproxy_version: 3.2.17-alpine@sha256:0c32ec9e64a3bbacb2a1a28afbc3d46032d905bf74ccb745b45488ff41ee9a6b

karo_compose_proxy_haproxy_config_raw: |
  # haproxy config

# qbittorrent

karo_compose_qbittorrent_enabled: false
karo_compose_qbittorrent_image: docker.io/qbittorrentofficial/qbittorrent-nox
karo_compose_qbittorrent_version: 5.1.4-1@sha256:41888f4e05646ace98aeaff01a7bbec714e2e6082ab273fd4af0d1210352ea2c
karo_compose_qbittorrent_domain: "qbittorrent.{{ karo_compose_root_domain }}"

karo_compose_qbittorrent_downloads_path: "" # e.g. /media/drive1/data/torrents

karo_compose_qbittorrent_webui_enabled: true

# qbittorrent qui

karo_compose_qbittorrent_qui_image: ghcr.io/autobrr/qui
karo_compose_qbittorrent_qui_version: v1.17.0@sha256:fb3832e68f66b056e1b049d16c40732661e7b73999bc642d4b11469a3ebbabd3
karo_compose_qbittorrent_qui_domain: "qui.{{ karo_compose_root_domain }}"
karo_compose_qbittorrent_qui_log_level: info # trace, debug, info, warn, error

karo_compose_qbittorrent_qui_session_secret: "" # secret (`openssl rand -hex 16`)

karo_compose_qbittorrent_qui_oidc_client_id: ""
karo_compose_qbittorrent_qui_oidc_client_secret: ""

# radarr

karo_compose_radarr_enabled: false
karo_compose_radarr_image: docker.io/linuxserver/radarr
karo_compose_radarr_version: 6.1.1.10360-ls300@sha256:b01097ad2d948c9f5eca39eb60bb529e2e55b0738c4bf7db09383bef0abab59d
karo_compose_radarr_domain: "radarr.{{ karo_compose_root_domain }}"
karo_compose_radarr_forward_auth_enabled: true

karo_compose_radarr_data_path: "" # e.g. /media/drive1/data

# seerr

karo_compose_seerr_enabled: false
karo_compose_seerr_image: ghcr.io/seerr-team/seerr
karo_compose_seerr_version: preview-new-oidc@sha256:a14a9c326881fdce70b00df3fc095f5b5b128f5552677f677cd3788e757fb4e6
karo_compose_seerr_domain: "seerr.{{ karo_compose_root_domain }}"
karo_compose_seerr_log_level: info # debug, info, warn, error

# sonarr

karo_compose_sonarr_enabled: false
karo_compose_sonarr_image: docker.io/linuxserver/sonarr
karo_compose_sonarr_version: 4.0.17.2952-ls309@sha256:3580aec3802c915f0f819a88d5099abce61734b925732b8393d176b5dc561020
karo_compose_sonarr_domain: "sonarr.{{ karo_compose_root_domain }}"
karo_compose_sonarr_forward_auth_enabled: true

karo_compose_sonarr_data_path: "" # e.g. /media/drive1/data

# whoami

karo_compose_whoami_enabled: false
karo_compose_whoami_image: docker.io/traefik/whoami
karo_compose_whoami_version: v1.11.0@sha256:200689790a0a0ea48ca45992e0450bc26ccab5307375b41c84dfc4f2475937ab
karo_compose_whoami_domain: "whoami.{{ karo_compose_root_domain }}"
karo_compose_whoami_forward_auth_enabled: false
