# SPDX-FileCopyrightText: © 2026 hazzuk
#
# SPDX-License-Identifier: AGPL-3.0-only

# Configuration file for `reuse`, a compliance tool for the REUSE spec.
# See https://reuse.readthedocs.io/ for more information.

# Commands:
# - `reuse download --all`  Download all missing licenses
# - `reuse lint`            Lint the directory for REUSE compliance

version = 1

# uncopyrightable files
[[annotations]]
path = [
  ".gitattributes",
  ".gitignore",
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"
