# SPDX-FileCopyrightText: © 2025 hazzuk
#
# SPDX-License-Identifier: AGPL-3.0-only

---

- name: Manage system setup
  hosts: server
  become: true
  tags: install
  roles:
    - karo-system
    - karo-nftables
    - karo-ssh
    - karo-git
    - karo-docker

- name: Manage compose stacks
  hosts: server
  become: true
  tags: compose
  roles:
    - karo-compose
