# SPDX-FileCopyrightText: 2025 hazzuk
#
# SPDX-License-Identifier: AGPL-3.0-only

---

- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart systemd-modules-load
  ansible.builtin.systemd_service:
    name: systemd-modules-load.service
    state: restarted

- name: Reload sysctl config
  ansible.builtin.command:
    argv:
      - /sbin/sysctl
      - -p
      - /etc/sysctl.d/karo.conf
  changed_when: true
