# SPDX-FileCopyrightText: 2025 hazzuk
#
# SPDX-License-Identifier: AGPL-3.0-only

---

- name: "Create compose stack directory for {{ stack }}"
  ansible.builtin.file:
    path: "/srv/docker/{{ group }}/{{ stack }}"
    mode: "0774"
    state: directory

- name: "Deploy compose templates for {{ stack }}"
  ansible.builtin.template:
    src: "{{ template.src }}"
    dest: "/srv/docker/{{ group }}/{{ stack }}/{{ template.path | splitext | first }}"
    mode: "0644"
  loop_control:
    loop_var: template
    label: "{{ template.path }}"
  with_community.general.filetree: ../templates/{{ group }}/{{ stack }}/
