# SPDX-FileCopyrightText: 2025 hazzuk
#
# SPDX-License-Identifier: AGPL-3.0-only

# https://docs.ansible.com/projects/ansible/latest/collections/community/docker/docker_compose_v2_module.html

---

- name: Check docker directory status
  ansible.builtin.stat:
    path: /srv/docker
  register: docker_dir

- name: Assert docker setup
  ansible.builtin.assert:
    that: docker_dir.stat.exists
    fail_msg: "Docker directory not present, run `just install` to setup Docker."
    quiet: true

- name: Define expanded stack list
  ansible.builtin.set_fact:
    karo_compose_stacks_expanded: |
      {%- set expanded_stacks = [] -%}
      {%- for group in karo_compose_stack_groups -%}
      {%-   for stack in lookup('vars', group) -%}
      {%-     set _ = expanded_stacks.append({
                'group': group,
                'name': stack
              }) -%}
      {%-   endfor -%}
      {%- endfor -%}
      {{ expanded_stacks }}

- name: Assert stack name
  ansible.builtin.assert:
    that: karo_compose_justfile_stack in (
        karo_compose_stacks_expanded | map(attribute='name') | list
        + ['all']
      )
    fail_msg: "Invalid stack name '{{ karo_compose_justfile_stack }}'."
    quiet: true

- name: Down stacks
  become: true
  become_user: dockeruser
  tags: down
  block:
    - name: Down docker compose stacks
      ansible.builtin.include_tasks: down.yml
      loop: "{{ karo_compose_stacks_expanded | reverse }}"
      loop_control:
        label: "{{ item.name }}"
      vars:
        stack: "{{ item.name }}"
        group: "{{ item.group }}"
      when:
        - lookup('vars', 'karo_compose_' ~ stack ~ '_enabled') | default(false)
        - karo_compose_justfile_stack in [stack, 'all']

- name: Deploy stacks
  become: true
  become_user: dockeruser
  tags: deploy
  block:
    - name: Deploy docker compose stacks
      ansible.builtin.include_tasks: deploy.yml
      loop: "{{ karo_compose_stacks_expanded }}"
      loop_control:
        label: "{{ item.name }}"
      vars:
        stack: "{{ item.name }}"
        group: "{{ item.group }}"
      when:
        - lookup('vars', 'karo_compose_' ~ stack ~ '_enabled') | default(false)
        - karo_compose_justfile_stack in [stack, 'all']

- name: Create stacks
  become: true
  become_user: dockeruser
  tags: up
  block:
    - name: Up docker compose stacks
      ansible.builtin.include_tasks: up.yml
      loop: "{{ karo_compose_stacks_expanded }}"
      loop_control:
        label: "{{ item.name }}"
      vars:
        stack: "{{ item.name }}"
        group: "{{ item.group }}"
        secrets: "{{ lookup('vars', 'karo_compose_' ~ stack ~ '_secrets', default={}) | dict2items }}"
      when:
        - lookup('vars', 'karo_compose_' ~ stack ~ '_enabled') | default(false)
        - karo_compose_justfile_stack in [stack, 'all']

  always:
    - name: Discard tmpfs secrets directory
      ansible.builtin.file:
        path: "/run/user/1001/karo/compose"
        state: absent
      when: secrets_dir | default(false)
      changed_when: false
