# SPDX-FileCopyrightText: 2025 hazzuk
#
# SPDX-License-Identifier: AGPL-3.0-only

# https://docs.ansible.com/projects/ansible/latest/collections/community/docker/docker_compose_v2_module.html

---

# setup

- name: Register docker directory status
  ansible.builtin.stat:
    path: /srv/docker
  register: docker_dir

- name: Assert docker setup
  ansible.builtin.assert:
    that: docker_dir.stat.exists
    fail_msg: "Docker directory not present, run `just install` to setup Docker."
    quiet: true

- name: Assert defined stack group names
  ansible.builtin.assert:
    that:
      - stack_group_lookup is not false
      - stack_group_lookup | type_debug == "list"
    fail_msg: "Invalid stack group '{{ stack_group }}' in 'karo_compose_stack_groups'."
    quiet: true
  loop: "{{ karo_compose_stack_groups }}"
  loop_control:
    loop_var: stack_group
    label: "karo_compose_stack_groups -> {{ stack_group }}"
  vars:
    stack_group_lookup: "{{ lookup('vars', stack_group, default=false) }}"

- name: Assert symlinked stack groups declared
  ansible.builtin.assert:
    that: stack_group_dir.path in karo_compose_stack_groups
    fail_msg: "Stack group '{{ stack_group_dir.path }}' missing from 'karo_compose_stack_groups'."
    quiet: true
  loop: "{{ query('filetree', '../templates', exclude='^\\.gitkeep$') }}"
  loop_control:
    loop_var: stack_group_dir
    label: "templates/{{ stack_group_dir.path }}/"

- name: Set expanded stack list
  ansible.builtin.set_fact:
    karo_compose_expanded_stacks: |
      {% set expanded_stacks = [] %}
      {% for group in karo_compose_stack_groups %}
      {%   for stack in lookup('vars', group) %}
      {%     set _ = expanded_stacks.append({
                'enabled': lookup('vars', group ~ '_' ~ stack ~ '_enabled'),
                'group': group,
                'name': stack,
                'namespace': group ~ '_' ~ stack,
                'path': group ~ '/' ~ stack,
              }) %}
      {%   endfor %}
      {% endfor %}
      {{ expanded_stacks }}

- name: Assert supplied stack name
  ansible.builtin.assert:
    that: karo_compose_justfile_stack in (
        karo_compose_expanded_stacks | map(attribute='name') | list
        + ['all']
      )
    fail_msg: "Invalid stack name '{{ karo_compose_justfile_stack }}'."
    quiet: true

# actions

- name: Down stacks
  become: true
  become_user: dockeruser
  tags: down
  block:
    - name: Down compose stacks
      ansible.builtin.include_tasks: down.yml
      loop: "{{ karo_compose_expanded_stacks | reverse }}"
      loop_control:
        loop_var: stack
        label: "{{ stack.name }}"
      when:
        - stack.enabled
        - karo_compose_justfile_stack in [stack.name, 'all']

- name: Up stacks
  become: true
  become_user: dockeruser
  tags: up
  block:
    - name: Up compose stacks
      ansible.builtin.include_tasks: up.yml
      loop: "{{ karo_compose_expanded_stacks }}"
      loop_control:
        loop_var: stack
        label: "{{ stack.name }}"
      vars:
        stack_host_vars: "{{ lookup('vars', stack.namespace ~ '_stack') }}"
        stack_defaults: "{{ lookup('vars', stack.namespace ~ '_stack_defaults') }}"
        stack_secrets: "{{ query('filetree', '../templates/' ~ stack.path ~ '/secrets') }}"
        karo_compose_secrets_path: "/run/user/1001/karo-compose/{{ stack.path }}"
      when:
        - stack.enabled
        - karo_compose_justfile_stack in [stack.name, 'all']

  always:
    - name: Discard tmpfs secrets directory
      ansible.builtin.file:
        path: "/run/user/1001/karo-compose"
        state: absent
      when: secrets_dir | default(false)
      changed_when: false
