# SPDX-FileCopyrightText: 2025 hazzuk
#
# SPDX-License-Identifier: AGPL-3.0-only

---

- name: Prepare secrets
  when:
    - secrets | length > 0
    - secrets_dir is undefined
  block:
    - name: Create tmpfs secrets directory
      ansible.builtin.file:
        path: /run/user/1001/karo/compose
        state: directory
        mode: "0700"

    - name: Mark secrets directory as created
      ansible.builtin.set_fact:
        secrets_dir: true

- name: Create secrets for {{ stack }}
  ansible.builtin.copy:
    dest: "/run/user/1001/karo/compose/{{ secret.key }}"
    content: "{{ secret.value }}"
    mode: "0644"
  loop: "{{ secrets }}"
  loop_control:
    loop_var: secret
    label: "{{ secret.key }}"

- name: Up compose stack {{ stack }}
  community.docker.docker_compose_v2:
    docker_host: unix:///run/user/1001/docker.sock
    project_src: "/srv/docker/{{ group }}/{{ stack }}"
    state: present # docker compose up
