# SPDX-FileCopyrightText: 2025 hazzuk
#
# SPDX-License-Identifier: AGPL-3.0-only

---

- name: Create secrets for {{ stack }}
  become: true
  become_user: dockeruser
  tags: up
  ansible.builtin.copy:
    dest: "/run/user/1001/karo/compose/{{ secret.key }}"
    content: "{{ secret.value }}"
    mode: "0644"
  loop: "{{ secrets }}"
  loop_control:
    loop_var: secret
    label: "{{ secret.key }}"

- name: Up compose stack {{ stack }}
  become: true
  become_user: dockeruser
  tags: up
  community.docker.docker_compose_v2:
    docker_host: unix:///run/user/1001/docker.sock
    project_src: "/srv/docker/{{ group }}/{{ stack }}"
    state: present # docker compose up
