# SPDX-FileCopyrightText: 2025 - 2026 hazzuk
#
# SPDX-License-Identifier: AGPL-3.0-only

---

karo_compose_justfile_stack: all

# docker will start stacks in this order
# docker will stop stacks in reverse order
# karo_compose_stack_groups:
#   - hazzuk_core
#   - hazzuk_extra

karo_compose_restart_policy: unless-stopped

karo_compose_timezone: "Europe/London"

karo_compose_root_domain: example.com

karo_compose_auth:
  provider_name: PocketID
  admin_group: admin
  subdomain: auth

karo_compose_oidc:
  domain: "{{ karo_compose_auth.subdomain }}.{{ karo_compose_root_domain }}" # e.g. auth.example.com
  url: "https://{{ karo_compose_oidc.domain }}" # e.g. https://auth.example.com
  authorization:
    path: "/authorize"
    url: "{{ karo_compose_oidc.url }}{{ karo_compose_oidc.authorization.path }}"
  discovery:
    path: "/.well-known/openid-configuration"
    url: "{{ karo_compose_oidc.url }}{{ karo_compose_oidc.discovery.path }}"
  token:
    path: "/api/oidc/token"
    url: "{{ karo_compose_oidc.url }}{{ karo_compose_oidc.token.path }}"
  userinfo:
    path: "/api/oidc/userinfo"
    url: "{{ karo_compose_oidc.url }}{{ karo_compose_oidc.userinfo.path }}"
  logout:
    path: "/api/oidc/end-session"
    url: "{{ karo_compose_oidc.url }}{{ karo_compose_oidc.logout.path }}"
  certificate:
    path: "/.well-known/jwks.json"
    url: "{{ karo_compose_oidc.url }}{{ karo_compose_oidc.certificate.path }}"
