# SPDX-FileCopyrightText: © 2026 hazzuk
#
# SPDX-License-Identifier: AGPL-3.0-only

---

# login required for docker hardened images
karo_docker_login_enabled: true

# docker account credentials
karo_docker_login_username: ""
karo_docker_login_token: ""
