# ~/.bash_logout: executed by bash(1) when login shell exits.

# when leaving the console clear the screen to increase privacy

if [ "$SHLVL" = 1 ]; then
    [ -x /usr/bin/clear_console ] && /usr/bin/clear_console -q
fi

# karo-stack

# clean-up vault password on logout
export P="/run/user/1000/karo-stack/vault_pass"; [ -e "$P" ] && shred -u "$P" >/dev/null 2>&1 || true
